name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: 20
          pnpm_v: 9
          run_install: true
      - name: Build
        run: pnpm run ci:build
      - name: Check Api
        run: pnpm run ci:api-check
      - name: Publish
        run: pnpm publish --no-git-checks

#   publish-jsr:
#     runs-on: ubuntu-latest
#     needs: publish-npm
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Publish
#         run: npx jsr publish --config jsr.json
