name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: 20
          pnpm_v: 9
          run_install: true
      - name: Unit test
        run: pnpm run ci:test
      - name: Build
        run: pnpm run -r ci:build
      - name: Install browser
        run: pnpm playwright install chromium webkit firefox --with-deps
        working-directory: "./e2e"
      - name: E2E test
        continue-on-error: true
        run: pnpm run ci:e2e
        id: e2e
        working-directory: ./e2e
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report/
      - name: Result
        if: ${{steps.e2e.outcome=='failure'}}
        run: exit 1
